### ISSUE TITLE
README.md correction

### ISSUE THREAD

**Issue by gogitgo** [notoriousbdg/hassio-addons#11]
First of all, THANKS for getting this add-on working!!

Steps 5 and 6 in the readme have entries for iframe_panel:, which should be panel_iframe:.

**Comment by notoriousbdg** [comment]
Fixed with https://github.com/notoriousbdg/hassio-addons/commit/248baa11fd625372e42248c9afa820eab1019476

**Comment by notoriousbdg** [comment]
Thanks for reporting that!
