### ISSUE TITLE
webui

### ISSUE THREAD

**Issue by pvizeli** [notoriousbdg/hassio-addons#13]
You can use:
`"webui": "http://[HOST]:[PORT:1880]"` -> `"webui": "[PROTO:ssl]://[HOST]:[PORT:1880]"`

It will now look into options -> ssl and change the correct proto depend of user config.

**Comment by notoriousbdg** [comment]
Very cool.  Implemented in https://github.com/notoriousbdg/hassio-addons/commit/248baa11fd625372e42248c9afa820eab1019476.
