### ISSUE TITLE
 Login attempt or request with invalid authentication from 127.0.0.1

### ISSUE THREAD

**Issue by CaCu15** [notoriousbdg/hassio-addons#22]
Greetings,

and thanks a lot for creating this great add-on. I love using node-red to define my automations. But I'm facing a problem currently:

If the Node-Red add-on is running it obviously tries to login to 127.0.0.1 with invalid credentials. My homeassistant.log is spammed with entries like the following one: 

`2017-12-23 17:41:09 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 127.0.0.1
`
I'm getting 1 of this entries every 2-3 seconds...

Do you have an idea, what's going wrong here?

**Comment by notoriousbdg** [comment]
If you stop Node-RED, do the errors stop?  Have you verified that you have the correct credentials setup in Node-RED?

**Comment by CaCu15** [comment]
I solved this with a complete new setup of HASSIO. The old setup showed some strange behaviour. Thx for your help.
