### ISSUE TITLE
Can't install Node-Red on latest hass.io for rpi

### ISSUE THREAD

**Issue by etricky** [notoriousbdg/hassio-addons#24]
Hi

When I try to install the Node-Red addon it fails. Here are the logs I get:
`18-01-03 14:14:08 INFO (SyncWorker_1) [hassio.dock.addon] Start docker addon homeassistant/armhf-addon-configurator with version 0.2.3
18-01-03 14:36:23 INFO (SyncWorker_3) [hassio.dock.addon] Start build 27e642c6/armhf-addon-nodered:0.1.6
18-01-03 14:36:33 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 410, in start
    resp = yield from self._request_handler(request)
  File "/usr/lib/python3.6/site-packages/aiohttp/web.py", line 325, in _handle
    resp = yield from handler(request)
  File "/usr/lib/python3.6/site-packages/aiohttp/web_middlewares.py", line 93, in impl
    return (yield from handler(request))
  File "/usr/lib/python3.6/site-packages/hassio/api/util.py", line 33, in wrap_api
    answer = await method(api, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/hassio/addons/addon.py", line 515, in install
    if not await self.docker.install(self.last_version):
  File "/usr/lib/python3.6/site-packages/hassio/dock/util.py", line 18, in wrap_api
    return await method(api, *args, **kwargs)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/site-packages/hassio/dock/addon.py", line 251, in _install
    return self._build(tag)
  File "/usr/lib/python3.6/site-packages/hassio/dock/addon.py", line 264, in _build
    image = self.docker.images.build(**build_env.get_docker_args(tag))
  File "/usr/lib/python3.6/site-packages/docker/models/images.py", line 179, in build
    raise BuildError(chunk['error'])
docker.errors.BuildError: failed to register layer: open /var/lib/docker/aufs/layers/33631632f31d6941d898203a2729fd3d068e0a88ea55ceb5b06647740911e034: no such file or directory
`

I'm running hass.io on a raspberry pi using the available image from [here](https://github.com/home-assistant/hassio-build/releases/download/1.1/resinos-hassio-1.1-raspberrypi.img.bz2) and I have the latest version for homeassistant (0.60) and supervisor (0.78).

Any idea on how to fix it?

Cheers,
Ricardo

**Comment by notoriousbdg** [comment]
Not sure about that one.  It kind of sounds like it might be a storage issue.  Can you verify you have free space on your sdcard?  If so, then maybe try a new sdcard.

**Comment by etricky** [comment]
I don't believe it's a storage issue as none of the partitions is full and it's a 16G sdcard.

`core-ssh:~# df -h
Filesystem                Size      Used Available Use% Mounted on
none                     13.9G      1.7G     11.5G  13% /
tmpfs                   240.7M     48.0K    240.6M   0% /dev
tmpfs                   240.7M         0    240.7M   0% /sys/fs/cgroup
/dev/mmcblk0p2          294.1M    224.6M     50.0M  82% /dev/init
/dev/mmcblk0p6           13.9G      1.7G     11.5G  13% /data
/dev/mmcblk0p6           13.9G      1.7G     11.5G  13% /config
/dev/mmcblk0p6           13.9G      1.7G     11.5G  13% /ssl
/dev/mmcblk0p6           13.9G      1.7G     11.5G  13% /addons
/dev/mmcblk0p6           13.9G      1.7G     11.5G  13% /backup
/dev/mmcblk0p6           13.9G      1.7G     11.5G  13% /share
/dev/mmcblk0p6           13.9G      1.7G     11.5G  13% /etc/resolv.conf
/dev/mmcblk0p6           13.9G      1.7G     11.5G  13% /etc/hostname
/dev/mmcblk0p6           13.9G      1.7G     11.5G  13% /etc/hosts
shm                      64.0M         0     64.0M   0% /dev/shm
tmpfs                   240.7M     48.0K    240.6M   0% /proc/latency_stats
tmpfs                   240.7M     48.0K    240.6M   0% /proc/timer_list
tmpfs                   240.7M     48.0K    240.6M   0% /proc/timer_stats
tmpfs                   240.7M     48.0K    240.6M   0% /proc/sched_debug
tmpfs                   240.7M         0    240.7M   0% /sys/firmware
`

**Comment by MrOBM** [comment]
I had the same issue, you need to update the host OS to 1.1, go to advanced settings and update the host OS.

**Comment by etricky** [comment]
@MrOBM I already have OS 1.1 so that's not the cause. I will try to hassio on a different sdcard.

**Comment by PierreScerri** [comment]
Hi
I have it on a different SDcard than etricky and I am getting the same result.

I actually had it working at one point but I decided to remove it .  I started again with a clean Hassio install.  The first time I try to install the Node Red add-on it takes forever and does not install.  Subsequent attempts only last a few seconds.  I get the same errors as etricky.

**Comment by Quato38** [comment]
I have same problem as PierrScerri.
resinos 1.3 Hassio 0.65.5 Supervisor 1.3

**Comment by notoriousbdg** [comment]
The error points to a problem with one of the docker layers which suggests an issue with that file and/or the sdcard.  You can try rebuilding the addon to see if it can rebuild the layer that's bad.  If that doesn't work, try a different sdcard and verify that your power supply is adequate.

**Comment by Quato38** [comment]
well, NOW its works. It take a long time for the add on to install, waited an hour and the add-on was instaled. Works just fine now.

**Comment by iikay** [comment]
我也无法安装
