### ISSUE TITLE
The node 6 needs to be update

### ISSUE THREAD

**Issue by Smandurlo** [notoriousbdg/hassio-addons#26]
It seems it is the reason the palette node-red-contrib-home-assistant version 3 doesn't work...

How is it possible to do it from hass.io?

**Comment by notoriousbdg** [comment]
Fixed via c39fa4d497e90208f8d24085d9b5aae492614bf8.

**Comment by Resterday** [comment]
@notoriousbdg works for me now! Thanks for the quick turnaround.
