### ISSUE TITLE
Problems installing on Intel NUC with HassIO

### ISSUE THREAD

**Issue by scfigg** [notoriousbdg/hassio-addons#28]
I'm running HassIO on top of Ubuntu 16 on an Intel NUC. I've installed Node Red successfully on a RPi3 in the past, but running into an error when trying to install it on my NUC:

18-03-10 01:56:05 INFO (SyncWorker_5) [hassio.docker.addon] Start build 27e642c6/amd64-addon-nodered:0.1.10
18-03-10 01:56:06 ERROR (SyncWorker_5) [hassio.docker.addon] Can't build 27e642c6/amd64-addon-nodered:0.1.10: Please provide a source image with `from` prior to commit

Any sugggestions?

**Comment by notoriousbdg** [comment]
You need to upgrade docker.

**Comment by scfigg** [comment]
ugh, ok thanks. I followed the guide here to inistall HassIO over Ubuntu and installed docker.io. Not sure how to upgrade docker - linux novice.

`sudo apt-get install docker.io`

https://www.youtube.com/watch?v=EMOLDrL6_7Q&index=1&t=303s&list=PLOkeE2vyZtuKOKkK1RvCwnkHEbA1_r3jy

Any simple steps on what I can do to upgrade? I would imagine installing it with the above command would install the latest docker automatically? or is docker.io trash and I should be using something else?

**Comment by scfigg** [comment]
`hassio@hassio:~$ sudo apt-get upgrade docker.io
Reading package lists... Done
Building dependency tree
Reading state information... Done
docker.io is already the newest version (1.13.1-0ubuntu1~16.04.2).
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
`

**Comment by scfigg** [comment]
sorry for all the replies - I'm a Linux novice, but a little googling got me in the right direction. Was unable to uninstall docker.io and install docker-ce, which fixed the issue for me! And luckily my images/containers were still there, so no need to re-install HassIO! Node-Red successfully installed for me now. Thank you so much for the quick reply.
