### ISSUE TITLE
hassio snapshot fails with HA Bridge running

### ISSUE THREAD

**Issue by shindawg** [notoriousbdg/hassio-addons#3]
Hi notoriousbdg, I've noticed that when trying to perform a snapshot/backup of hassio while HA bridge is running it will hang the OS (observed this happening for a couple hrs). A hard reset is then required as you lose samba, ssh and web access while its trying to do the backup and  it never comes back. So i'm guessing when you do this because the services are still active it corrupts the OS layer because when it eventually comes back the supervisor logs report a lose of services such as tts, media, hardrive, etc and you can't remedy this as your not able to restart ssh or samba to get to any files and additional logs.

I was able to replicate this (not by choice) a couple times, so I took a step back and performed the following.

1. rebuilt and performed a hassio back without HA bridge installed - success (say 15 secs)
2. installed HA Bridge configured and then shut it down and performed a backup - success (2 min)
other components installed at the time. 
 - zwave
- samba
- ssh
- mqtt

So with a successful backup i then build a new hassio image and performed a restore from my backup. This was successful with the exception of HA bridge, this did not get re-install from the backup (the share folders and files did) even though it was present at the time of doing the backup??

It still seems that even though I had it turned off during the hassio backup process, this process still had problems dealing with the presence of HA bridge being installed.

apologies this is only observational as its difficult to capture logs during these events and I didn't think to grab the supervisor logs the first time

one last thing and i don't know if it makes any difference as I haven't tested this yet. This all happened using an older Pi 2 B+. I have since received a new Pi 3 B+ today (which handles hassio so much better)

Now that I know what's going on I can work around it, thought the info might be useful though.

Cheers

**Comment by notoriousbdg** [comment]
I have been creating snapshots daily for a couple weeks now (on a Pi 3), and I've never experienced this issue.  My guess is that your power supply isn't supplying stable/enough power for the Pi or your SD card is too slow.

All of the data needed to re-deploy HA Bridge is stored in /share/habridge, so as long as you have those files, you should be able to recover without needing the snapshot.

**Comment by shindawg** [comment]
Yeah I think your right, the performance difference between the Pi and Pi 3 is night and day, a lot of messages i was seeing on the Pi in hassio are no longer there. Same SD card, so no problem there.

retracting the issue as it appears that its not an application problem, but more directly related to the base metal performance that's trying to host it.

Cheers
