### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by cuihaijun** [notoriousbdg/hassio-addons#30]
Latest version on bwssystems github repo is 5.2.0
Using existing version '5.2.0'
Setting correct permissions
Parameters used:
  Server IP : 127.0.0.1
  Server Port : 80
  preferIPv4Stack : true
Starting Home Automation Bridge
/run.sh: line 55: /usr/bin/java: No such file or directory

**Comment by notoriousbdg** [comment]
I'm unable to repro.  Try clicking on rebuild on the addon details page.
