### ISSUE TITLE
persistant notificatio

### ISSUE THREAD

**Issue by run3peders3n** [notoriousbdg/hassio-addons#33]
Dont know if this is a bug or what, but when i use this to create a persitant notification node red chrash when i dismiss it it hass.io 
[{"id":"2a9636ce.c0ecba","type":"api-call-service","z":"6130676a.e4f1d8","name":"","server":"e893ec39.f42e","service_domain":"persistent_notification","service":"create","data":"{ \"title\": \"test\",\"message\": \"this is test\" }","mergecontext":"","x":475,"y":501,"wires":[[]]},{"id":"e893ec39.f42e","type":"server","z":"","name":"Home Assistant","url":"removed","pass":"removed"}]

**Comment by notoriousbdg** [comment]
What do you see in the addon logs?
