### ISSUE TITLE
Node red stops

### ISSUE THREAD

**Issue by iron-2** [notoriousbdg/hassio-addons#35]
Hello.
First, thank you for getting this into Hassio.
Since I updated to 0.1.11 though, it seems that Node-red stopps intermittently. Before I did the update it was running without any issues.

Anyone else have this problem?

**Comment by notoriousbdg** [comment]
It's hard to say without seeing logs.  The only issue I know of is https://github.com/AYapejian/node-red-contrib-home-assistant/issues/44.
