### ISSUE TITLE
Node-RED Unexpected Token error / wont start

### ISSUE THREAD

**Issue by MarcoBruh** [notoriousbdg/hassio-addons#36]
Hi, I just installed Node-RED on Hassio (Raspberry) 0.68.1.
Port forwarded 1880 to my internal raspberry IP adres.

Problem is when i start Node-RED it shows as started, but when i refresh the addons page it stopped again and showing the following error in the log file:

> [INFO] Disabling SSL
[INFO] Updating IDE Users
[INFO] Adding IDE User admin
[INFO] Updating HTTP Node User
[INFO] Adding HTTP Node User admin
[INFO] Disabling Projects
npm info it worked if it ends with ok
npm info using npm@5.6.0
npm info using node@v10.0.0
npm info lifecycle node-red-docker@1.0.0~prestart: node-red-docker@1.0.0
npm info lifecycle node-red-docker@1.0.0~start: node-red-docker@1.0.0
> node-red-docker@1.0.0 start /usr/src/node-red
> node $NODE_OPTIONS node_modules/node-red/red.js -v $FLOWS "--userDir" "/share/node-red"
Error loading settings file: /share/node-red/settings.js
/share/node-red/settings.js:3
       users: [
            ^
SyntaxError: Unexpected token :
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:646:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
npm info lifecycle node-red-docker@1.0.0~poststart: node-red-docker@1.0.0
npm info ok 

> 

I did try changing the username and password but with no luck. The above log is based on the install default settings.

Marco

**Comment by notoriousbdg** [comment]
Try renaming your settings.js file at \\hassio.local\data\node-red then restarting the addon.  If that doesn't fix it, your password might have a special character that's breaking things.  Using a password with different special characters might help.

**Comment by MarcoBruh** [comment]
Not at home a.t.m. but will try this asap and report back 👍
