### ISSUE TITLE
Can't install Node-RED

### ISSUE THREAD

**Issue by NielsFeenstra** [notoriousbdg/hassio-addons#37]
After adding the repo on a Esxi 6.5/Ubuntu/docker-ce/hass.io configuration I cant install Node-RED.

When I push the install button nothing happends, the system log from hass.io end with;

"FileNotFoundError: [Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/']"

**Comment by notoriousbdg** [comment]
Not sure what could cause that.  Typically that would be a permission issue, but that shouldn't be an issue in the container as it runs as root.

**Comment by OmgImAlexis** [comment]
I think I may have the same issue.

**Comment by notoriousbdg** [comment]
Someone posted more complete logs on the forums that suggest the issue might be with the hassio supervisor and not this addon.  It looks like there are several people affected now.  @pvizeli, do you think this could be an issue with the latest supervisor update?

**Comment by notoriousbdg** [comment]
I've tried and failed to repro on both hassio on a RPI 3B and hassio on Ubuntu 16.04 with supervisor version 103.3.



.

**Comment by OmgImAlexis** [comment]
Is there anything I can do to provide logs for you?

**Comment by pvizeli** [comment]
Can you 0ost the full log of supervisor?

**Comment by pvizeli** [comment]
And dmesg after you hit the button. Plase make a issue on hassio repoditory.

**Comment by pvizeli** [comment]
I have fix it. Rerun the installer or update the apparmor profile and it works.

**Comment by NielsFeenstra** [comment]
How can i update the apparmor profile?

**Comment by pvizeli** [comment]
`Rerun the installer`
