### ISSUE TITLE
access to filesystem? (logging)

### ISSUE THREAD

**Issue by neslekkim** [notoriousbdg/hassio-addons#38]
I'm trying to use the file output, to do some debugging, but I cannot find out where the files are?
I guess its some  isolation between node-red and hassio?, so the files are inside an docker or something that makes them not available outside?

**Comment by notoriousbdg** [comment]
`/share` is available in node-red and the host.

**Comment by neslekkim** [comment]
ok, so I should be able to write directly to /share?, I tried to do /share/testfile.txt, but got nothing, or should I write in an subfolder inside the node-red folder?

**Comment by neslekkim** [comment]
ah, cool, it worked under a subfolder, thanks!
