### ISSUE TITLE
port exposition 

### ISSUE THREAD

**Issue by pickeld** [notoriousbdg/hassio-addons#4]
hey,
is it possible to expose more port to outside of the docker?
lets say i want to listen on UDP port xxx to trigger some action. 
the UDP  will never get to the docker unless you expose it.

what do you think?
thanks

**Comment by notoriousbdg** [comment]
Actually, I don't think you'll need to modify the container because the container is configured to use the host network.  It should just listen on whatever ports you configure.

**Comment by pickeld** [comment]
Actually you must specify the port in order the host be able to forward it you the container. 
In docker it works like this :
'docker run [image name] -p 80:80'
In this example the host forward any port 80 request to the  port 80 inside the container.

**Comment by pickeld** [comment]
So sending packet TO the ha bridge container (lets say port 9050) should be received?

**Comment by notoriousbdg** [comment]
Yes, if it's listening on 9050.

**Comment by pickeld** [comment]
i made a UDP input and UDP output. listening on port 9800 and sending on port 9801:
![image](https://user-images.githubusercontent.com/13360982/29489365-423ed3b0-8528-11e7-8da8-ad63cca27a5e.png)

i cant tell what is wrong but i never get the packet on my pc listening on port 9801
can you test it please on your setup please?

**Comment by notoriousbdg** [comment]
I thought you were talking about HA Bridge but your screenshot is Node-RED.  The Node-RED add-on is on the Docker bridge network, so it is only reachable on TCP/1880.  Are you looking to make Node-RED listen on arbitrary ports?

**Comment by pickeld** [comment]
yes, i was talking about node-red sorry for that, 
and for the other question, yes, im looking to listen on arbitrary ports.

**Comment by notoriousbdg** [comment]
Can you retry with the latest version of the addon?  It should work now with commit db27b8bf2b43d8ef4dc8cf17da172226d0d9a51c.
