### ISSUE TITLE
Node-RED Fail to start Segmentation fault

### ISSUE THREAD

**Issue by amasterstx** [notoriousbdg/hassio-addons#40]
I have fresh install of HA installed Node-RED as a add-on but getting the following in the log:
[INFO] Disabling SSL
[INFO] Updating IDE Users
[INFO] Adding IDE User admin
[INFO] Updating HTTP Node User
[INFO] Adding HTTP Node User admin
[INFO] Disabling Projects
/run.sh: line 122:    48 Segmentation fault      npm start -- --userDir /share/node-red

I have tried researching it but no luck and reinstall the add-on.  Also have tried removing settings.js

**Comment by amasterstx** [comment]
I have delete the node-red folder inside share and I am getting the following:
[INFO] Creating /share/node-red folder
[INFO] Creating default settings
[INFO] Disabling SSL
[INFO] Updating IDE Users
[INFO] Adding IDE User admin
[INFO] Updating HTTP Node User
[INFO] Adding HTTP Node User admin
[INFO] Disabling Projects
/run.sh: line 122:    50 Segmentation fault      npm start -- --userDir /share/node-red

It did recreate the folder and settings.js.  I have no existing node or flows as this is a fresh install of hassio.  

The only thing I am seeing error wise in system log is the following but I believe it to be tried to homebridge:

18-05-17 21:41:39 WARNING (MainThread) [hassio.api.proxy] Unknown Home-Assistant API access!
18-05-17 21:41:39 INFO (MainThread) [hassio.api.proxy] Home-Assistant EventStream start
18-05-17 21:41:39 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/states access from a0d7b954_homebridge
18-05-17 21:41:39 ERROR (MainThread) [hassio.api.proxy] Client error on API stream request Cannot connect to host 172.30.32.1:8123 ssl:False [Connection refused].
18-05-17 21:41:39 ERROR (MainThread) [hassio.api.proxy] Client error on API states request Cannot connect to host 172.30.32.1:8123 ssl:False [Connection refused].

Also I have to say THANK YOU for making this add-on as I was done with hassio because of how hard it is to make more advanced automation.  I saw a youtube of someone using this and decided to give it another try. So again THANK YOU for making this!!!

**Comment by notoriousbdg** [comment]
I'm glad you find it useful.  Can you try rebuilding the addon to see if that helps?

**Comment by amasterstx** [comment]
I have tried rebuilding before but now I am getting the following in the system log:
 18-05-19 17:43:59 ERROR (SyncWorker_10) [hassio.docker.addon] Can't build 27e642c6/armhf-addon-nodered:0.1.11: The command '/bin/sh -c apt-get update &&     apt-get install -y jq &&     npm install -g node-red-admin' returned a non-zero code: 1

**Comment by notoriousbdg** [comment]
Which platform are you running hassio on?

**Comment by amasterstx** [comment]
Raspberry Pi 2

**Comment by notoriousbdg** [comment]
I just released a new version of the addon.  Can you please test to see if fixes this issue?

**Comment by amasterstx** [comment]
OK it is working now thanks :)
