### ISSUE TITLE
Cannot edit config 

### ISSUE THREAD

**Issue by xundre** [notoriousbdg/hassio-addons#42]
My configuration does not seem to be editable for habridge. Every-time I save it , it reverts back to the old values.

**Comment by notoriousbdg** [comment]
The addon doesn't touch configuration.  It's stored at /share/habridge if you need to access it.  If the changes aren't persisting, you might be having issues with your sdcard.

**Comment by xundre** [comment]
thanks, I realized the issue was with location of the devices.db. Now that's resolved, I cannot get Habridge to register homeassistant , none of my homeassistant devices show up in habridge.
