### ISSUE TITLE
url

### ISSUE THREAD

**Issue by filoor** [notoriousbdg/hassio-addons#44]
Hi,

My node-red is password protected and now i try to send my sonos a url that i create from google tts
"http://192.168.0.119:1880/tts/tts.mp3" but it will not play because the password protection.
Is there a work around for it

**Comment by notoriousbdg** [comment]
Try removing authentication from http_node_user section of the addon config.  Another option is to store your file at /config/www so you can access it at http://hassio.local/local.

**Comment by filoor** [comment]
Hi,

Thanks "http://hassio.local:1880/tts" did help with the errors 
only i will see now on sonos player that the next message ""tts.mp3 is not available anymore on hassio.local:1880"

**Comment by notoriousbdg** [comment]
If disabling authentication for http_node_user didn't fix it, then I suggest that you ask the author of that node for suggestions.
