### ISSUE TITLE
node-red: Builtin nodes do not update when rebuilding container

### ISSUE THREAD

**Issue by simonszu** [notoriousbdg/hassio-addons#47]
I want to update the Twitter node to 1.0.1, since this release fixes Twitter's recently activated API changes/limits. Unfortunately, the Twitter node is builtin, and cannot be upgraded by the "Manage palette" menu. 
According to the FAQ, i need to rebuild the container on the Hassio addon management page for the node red addon. But after i have triggered the rebuild and the container is up and running again, the Twitter node isn't upgraded at all. How can i manage the update, then?

**Comment by notoriousbdg** [comment]
The node-red team needs to update their docker image to include that update.  I suggest opening an issue at https://github.com/node-red/node-red-docker/issues to see if they'll build a new image with the updated node.
