### ISSUE TITLE
Node-Red Change port number

### ISSUE THREAD

**Issue by MPopti0n** [notoriousbdg/hassio-addons#48]
Hass.io 0.72.1 running on RPi3
Node red addon 0.1.12

Since last update of Hassio (0.72.1) or Node red addon (0.1.12)  I don't know why but Node-Red crash before starting and I belive the port 1880 is already in use by some other process.

Is it possible to change the default port manually by something else?

And that's the log, note that I didn't change anything in my config before the error

```
Failed to start server:
/usr/src/node-red/node_modules/mustache/mustache.js:268
    for (var i = 0, numU�kens =��kens.length; i < numTokeos; ++i) {
                        ^
SyntaxError: Invalid or unexpected token
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/src/node-red/node_modules/node-red/red/api/editor/ui.js:19:16)
npm info lifecycle node-red-docker@1.0.0~start: Failed to exec start script
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-red-docker@1.0.0 start: `node $NODE_OPTIONS node_modules/node-red/red.js -v $FLOWS "--userDir" "/share/node-red"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-red-docker@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by notoriousbdg** [comment]
You can change the port by editing /share/node-red/settings.js and changing the uiPort variable to the port you want to use.  Not sure what would cause that error, but my first guess is that your sdcard is failing.

**Comment by MPopti0n** [comment]
God 😂 I was in the config file, that’s why! My SD seems ok and it’s working like a charm with another port... Don’t know why but had a similar issue on PC and that resolve it too 

Thanks 😊
