### ISSUE TITLE
Node Red not  working, no clue

### ISSUE THREAD

**Issue by PauloPC** [notoriousbdg/hassio-addons#49]
Wen I try to open  the we ui  I got the message mi  HA localIp:1880  refuse a conection

Nod Red Log:

[INFO] Disabling SSL
[INFO] Updating IDE Users
[INFO] Adding IDE User Devuser
[INFO] Updating HTTP Node User
[INFO] Adding HTTP Node User Devuser
[INFO] Disabling Projects
[INFO] Attempting to install/update nodes: node-red-contrib-home-assistant
npm info it worked if it ends with ok
npm info using npm@5.0.3
npm info using node@v8.1.3
npm http fetch GET 200 https://registry.npmjs.org/node-red-contrib-home-assistant 452ms
npm http fetch GET 200 https://registry.npmjs.org/node-red-contrib-home-assistant/-/node-red-contrib-home-assistant-0.3.2.tgz 250ms
npm info lifecycle node-red-contrib-home-assistant@0.3.2~preuninstall: node-red-contrib-home-assistant@0.3.2
npm info lifecycle node-red-contrib-home-assistant@0.3.2~uninstall: node-red-contrib-home-assistant@0.3.2
npm info lifecycle node-red-contrib-home-assistant@0.3.2~postuninstall: node-red-contrib-home-assistant@0.3.2
npm info lifecycle node-red-contrib-home-assistant@0.3.2~preinstall: node-red-contrib-home-assistant@0.3.2
npm info linkStuff node-red-contrib-home-assistant@0.3.2
npm info lifecycle node-red-contrib-home-assistant@0.3.2~install: node-red-contrib-home-assistant@0.3.2
npm info lifecycle node-red-contrib-home-assistant@0.3.2~postinstall: node-red-contrib-home-assistant@0.3.2
npm info lifecycle undefined~preshrinkwrap: undefined
npm info lifecycle undefined~shrinkwrap: undefined
npm info lifecycle undefined~postshrinkwrap: undefined
npm WARN node-red-project@0.0.1 No repository field.
npm WARN node-red-project@0.0.1 No license field.
npm info ok 
npm info it worked if it ends with ok
npm info using npm@5.0.3
npm info using node@v8.1.3
npm info lifecycle node-red-docker@1.0.0~prestart: node-red-docker@1.0.0
npm info lifecycle node-red-docker@1.0.0~start: node-red-docker@1.0.0
> node-red-docker@1.0.0 start /usr/src/node-red
> node $NODE_OPTIONS node_modules/node-red/red.js -v $FLOWS "--userDir" "/share/node-red"
Error loading settings file: /share/node-red/settings.js
/share/node-red/settings.js:3
       users: [
            ^
SyntaxError: Unexpected token :
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/src/node-red/node_modules/node-red/red.js:115:20)
npm info lifecycle node-red-docker@1.0.0~poststart: node-red-docker@1.0.0
npm info ok 

configuration.yaml:

  nodered_flows:
     title: 'Node-RED Flows'
     url: 'http://hassio.local:1880'
     icon: mdi:nodejs

**Comment by notoriousbdg** [comment]
Try deleting /share/node-red/settings.js then restarting the addon.

**Comment by PauloPC** [comment]
There is no /share/node-red/settings.js then restarting the add on in config file.

"{
  "ssl": false,
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "users": [
    {
      "username": "Devuser",
      "password": "senha12",
      "permissions": "*"
    }
  ],
  "http_node_user": [
    {
      "username": "Devuser",
      "password": "senha12"
    }
  ],
  "projects": false,
  "install_packages": [],
  "install_nodes": [
    "node-red-contrib-home-assistant"
  ],
  "uninstall_nodes": []
}"

**Comment by notoriousbdg** [comment]
Can you check again?  That error suggests the file is there and it's just malformed.  Deleting it and allowing the addon to recreate it should fix things.

Also, if that's your actual password, I recommend changing it ASAP.
