### ISSUE TITLE
Changes lost to NodeRed config

### ISSUE THREAD

**Issue by dethpickle** [notoriousbdg/hassio-addons#50]
This seems an awful lot like #42 for HABridge...

I'm new to node red and have been having a blast with it for the last couple days.  Thanks for making a nice plugin for Hassio to help lower the bar to entry.

I am having an odd issue with making config changes within the Hassio plugin section for your plugin.  Simple things - maybe initial things - worked like changing the password and such.  But when I try adding in new keys like `credentialSecret` or `paletteCategories`, they disappear as soon as I save and restart the plugin.

It does seem that all changes are lost if you don't stop the plugin before saving it.  But, even if I do, it surgically removes the new lines like: `"credentialSecret": "whatever",` and proceeds on it's merry way.

I've seen from your other issue comments that there is a `settings.js` over in /share/node-red, but I'm a little wary of changing that since the config in the plugin and the program's settings.js seem to have a lot of overlap and am not sure how they'll interact.

I'm looking to get an explicit credentialSecret on there as well as reorder the palette in the editor.  Please let me know where I might be going wrong.

Thanks!

Dave

**Comment by notoriousbdg** [comment]
`credentialSecret` and `paletteCategories` are not supported config options in the addon config, so hassio is likely removing them automatically.

You can modify settings.js, but a bit fragile because the addon uses sed to manipulate settings in the file.  Worst case, if something goes wrong, you can just delete settings.js, and the addon will recreate it on next start.

**Comment by dethpickle** [comment]
Ahh.  So I should be using settings.js.  I'll try not to disturb any of the other lines.  Thanks for the quick reply!

**Comment by dethpickle** [comment]
Worked fine.  I don't know the internal names of half the paletteCategories, so I'm guessing.  But the one's I'm guessing correctly are ordering up as I wished.  The "home assistant" palette comes in as 'home_assistant'.  The other custom nodes I've added are hit or miss for guessing their name.

Thanks for the point in the right direction!
