### ISSUE TITLE
Permissions error

### ISSUE THREAD

**Issue by vortex-uk** [notoriousbdg/hassio-addons#51]
Hi, 
NR stopped working on my RPi3 hass.io (0.72.1) this evening and the watchdog didn't seem to reboot it - came to look in the logs and I'm getting the following error **Unknown system error -117: Unknown system error -117, access '/share/node-red/node_modules/npm/node_modules/npm-audit-report**.

Tried a rebuild and erasing my settings.js to no avail - don't know if anyone's encountered similar or could suggest a solution? My automations have ground to a halt and the wife isn't happy that none of the Xiaomi Smart Buttons function any more!

**Logs**

> [INFO] Creating default settings
> [INFO] Enabling SSL
> [INFO] Updating IDE Users
> [INFO] Adding IDE User xxxxx
> [INFO] Updating HTTP Node User
> [INFO] Adding HTTP Node User xxxxx
> [INFO] Disabling Projects
> [INFO] Attempting to install/update nodes: node-red-contrib-home-assistant
> npm info it worked if it ends with ok
> npm info using npm@5.0.3
> npm info using node@v8.1.3
> npm http fetch GET 200 https://registry.npmjs.org/node-red-contrib-home-assistant 476ms
> npm http fetch GET 200 https://registry.npmjs.org/protoduck 106ms
> npm http fetch GET 200 https://registry.npmjs.org/genfun 74ms
> npm http fetch GET 200 https://registry.npmjs.org/npm-audit-report 59ms
> npm http fetch GET 200 https://registry.npmjs.org/console-control-strings 56ms
> npm WARN checkPermissions Missing write access to /share/node-red/node_modules/npm/node_modules/npm-audit-report
> npm WARN node-red-project@0.0.1 No repository field.
> npm WARN node-red-project@0.0.1 No license field.
> npm ERR! path /share/node-red/node_modules/npm/node_modules/npm-audit-report
> npm ERR! code Unknown system error -117
> npm ERR! errno -117
> npm ERR! syscall access
> npm ERR! Unknown system error -117: Unknown system error -117, access '/share/node-red/node_modules/npm/node_modules/npm-audit-report'
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2018-07-05T23_34_55_853Z-debug.log
> [ERROR] Can't install nodes!

**Comment by notoriousbdg** [comment]
Try rebooting first.  If that doesn't work, try deleting /share/node-red/node_modules/npm/node_modules/npm-audit-report.  If that doesn't work, it's probably time to replace your sdcard.
