### ISSUE TITLE
Error while trying to use raspi GPIO

### ISSUE THREAD

**Issue by nahiankhondoker** [notoriousbdg/hassio-addons#52]
Getting this "nrpgio python command not running" in the debug window while trying to use GPIO in a flow

**Comment by notoriousbdg** [comment]
GPIO cant be supported in the add-on until https://github.com/home-assistant/hassio/issues/432 is addressed in hassio.  You'll need to let Home Assistant manage GPIO for now.

**Comment by nahiankhondoker** [comment]
got it! thanks
