### ISSUE TITLE
"Can't install nodes!"

### ISSUE THREAD

**Issue by wlraider70** [notoriousbdg/hassio-addons#53]
Hi,

I've been using Nodered on my homeassisstant docker. I updated the HA yesterday and lost nodered. 
I eventually found these logs. 
The issue does not seem to be internet connectivity all my other containers are working fine, but I'm a bit new to docker as a whole.

I also tried downloading https://hub.docker.com/r/nodered/node-red-docker/ independitaly it has the same issues. 

```
[INFO] Disabling SSL,
[INFO] Updating IDE Users,
[INFO] Adding IDE User admin,
[INFO] Updating HTTP Node User,
[INFO] Adding HTTP Node User admin,
[INFO] Disabling Projects,
[INFO] Attempting to install/update nodes: node-red-contrib-home-assistant,
npm ERR! code ENOTFOUND,
npm ERR! errno ENOTFOUND,
npm ERR! network request to https://registry.npmjs.org/node-red-contrib-home-assistant failed, reason: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443,
npm ERR! network This is a problem related to network connectivity.,
npm ERR! network In most cases you are behind a proxy or have bad network settings.,
npm ERR! network ,
npm ERR! network If you are behind a proxy, please make sure that the,
npm ERR! network 'proxy' config is set properly.  See: 'npm help config',
,
npm ERR! A complete log of this run can be found in:,
npm ERR!     /root/.npm/_logs/2018-07-16T03_25_03_696Z-debug.log,
[ERROR] Can't install nodes!,
,
```

**Comment by notoriousbdg** [comment]
That looks like the same issue as #21.

**Comment by wlraider70** [comment]
I'm not running on a Pi, and I do not have dns system link that. I run my dns / dhcp off of my router. I guess docker handles some kind of internal DNS for the containers? I'm not so clear on how that magic happens.

**Comment by notoriousbdg** [comment]
It looks like there is something not working right with DNS.  It may help if you can troubleshoot DNS from inside the node-red container.  You can run `docker exec -it addon_27e642c6_nodered /bin/bash` on your host to get inside the container.

**Comment by wlraider70** [comment]
I think that my issue is beyond the scope of node-red, but I'll detail it now anyway.

1. I can't get container "addon_27e642c6_nodered " to start when the volumes are bound. If I remove the /data link I can start the container (I'm assuming this only blanks out my flows)

2. Form in the container I can ping ip but not dns. 
HOWEVER, according to portainer "addon_27e642c6_nodered" part of the network "host' as is plex & homeassistant. home assistant has the same pinging issue.

see networks
![image](https://user-images.githubusercontent.com/8108907/42796118-f3210a36-8955-11e8-965c-22df604a123b.png)
