### ISSUE TITLE
Node-Red cannot connect to Hass.io

### ISSUE THREAD

**Issue by ciB89** [notoriousbdg/hassio-addons#54]
### Problem/Motivation
Hassi.io 0.74.0 seems to have broke the API Login from Node-Red

**Expected behavior**
Node-Red connecting to Hass.io

**Actual behavior**
Node-Red cannot connect to Hass.io

```
24 Jul 10:09:38 - [error] [server:Home Assistant] Home assistant connection failed with error: Connection to home assistant could not be established with config: http://hassio/homeassistant <password redacted>
24 Jul 10:09:38 - [error] [server:Home Assistantx] Home assistant connection failed with error: Connection to home assistant could not be established with config: https://hassio/homeassistant <password redacted>
24 Jul 10:09:40 - [error] [server:Home Assistantx] Home assistant connection failed with error: Connection to home assistant could not be established with config: http://hassio/homeassistant <password redacted>
```

**Steps to reproduce**
Upgraded to Hass.io 0.74.0 and Node-red stopped working immediately. Enabled the new Auth system with legacy api support, did not make a difference. Attempted to connect with and without the api password.

**Proposed changes**
Unknown

**Comment by BasvanderPloeg01** [comment]
I'm having the same issue.

**Comment by grantalewis** [comment]
Also the same issue. Everything was working fine prior to 0.74.0. No settings were changed before upgrading. Not able to resolve the issue by downgrading to 0.74.0b4 via curl or to 0.73.2 via a locally-saved hass.io snapshot.

**Comment by markomannux** [comment]
same issue without upgrading

**Comment by notoriousbdg** [comment]
It's likely caused by an issue with the hassio supervisor.  Try updating your supervisor to 119 or newer.

**Comment by grantalewis** [comment]
Maybe I'm doing it wrong, but...

```
core-ssh:~# hassio supervisor update
ERROR
Version 118 is already in usecore-ssh:~# 
```

**Comment by efurban** [comment]
using ip instead of http://hassio/homeassistant fixed it.

**Comment by notoriousbdg** [comment]
I'm not planning to make any more changes to the add-ons.  I moved to native docker and there are alternative node-red add-ons available.

It looks like supervisor 118 changed how the API proxy works, which is why http://hassio/homeassistant isn't working anymore.  As @efurban mentioned, using the public hostname should get things working again.

**Comment by grantalewis** [comment]
@notoriousbdg thanks for the info. And thanks for your contributions to this project. I've been one of many who have benefitted from your hard work. Much appreciated!

As for using the IP address, I don't think that's an alternative for those of us using DuckDNS. I tried every variation possible earlier today without success. I think we'll have to wait for an update to HA.

**Comment by jdetmold** [comment]
The workaround does not seem to work for me with hassio and node red using ssl. it's not a firewall issue my local dns resolves the domain. I'm using a trusted cert.
before changing my domain my hassio system log was showing

WARNING (MainThread) [hassio.api.proxy] Unknown HomeAssistant API access!

after changing the domain in node red to https://sub.domain.com:8123 my hassio log shows
it's now showing 

INFO (MainThread) [hassio.api.security] /addons/a0d7b954_nodered/info access from a0d7b954_nodered

but my node red log still shows 

Home assistant connection failed with error: Connection to home assistant could not be established with config: https://sub.domain.com:8123 <password redacted>

**Comment by jdetmold** [comment]
I do run a local dns. it is working now but will revert to 115 anyway.
how does the supervisor update? it seems to do it automatically. When I left home this morning it was on 118, when I came back it was on 120. Also when the issue first presented I had not done any updates. ideally I would rather not auto update as things like this can pop up without being notices right away.

**Comment by notoriousbdg** [comment]
IIRC, the supervisor checks for updates and applies them every 24 hours.  AFAIK, there is on way to opt out of automatic updates.

**Comment by jdetmold** [comment]
thanks!

**Comment by jdetmold** [comment]
and broken again in 121

**Comment by notoriousbdg** [comment]
It appears that a token is now required to access the api proxy.  That essentially makes the api proxy unusable without making changes to the addon.

**Comment by ciB89** [comment]
The community node-red add-on works with the new API, just install the add on and configure it, install all the packages that you use for your flows, export and import your flows, restart node-red and you are good to go (deactivate the old node-red). Took my only like 5 minutes.
