### ISSUE TITLE
Adding security? 

### ISSUE THREAD

**Issue by mikehole** [notoriousbdg/hassio-addons#6]
Not really an issue more of a question...

Normally this is done by adding credentials to the config file. How could this be added to the add-on?

**Comment by notoriousbdg** [comment]
Which addon are you referring to?

**Comment by mikehole** [comment]
Doh, sorry Node Red

**Comment by Mikkelmoeller** [comment]
Any news?

**Comment by pickeld** [comment]
hey @notoriousbdg please make both habridge and node-red more secure by request username and password. (for example Terminal addon made it)
and if its possible please (i beg) make habridge to use ssl
what do you think?
thank you!

**Comment by notoriousbdg** [comment]
I plan to add authentication support to Node-RED when I have some free time.

HA Bridge would need to support SSL before I could add support in the addon.  Perhaps you could put a reverse proxy in front of your HA Bridge instead?

**Comment by pickeld** [comment]
@notoriousbdg thank you.
have you tried that? ive been and it made a lot of problems for me since im allready using nginx as a proxy to my hass instance.,.. what about authentication for ha-bridge? (usrname & pass)

**Comment by notoriousbdg** [comment]
No, I haven't.  Since the author strongly discourages exposing HA Bridge to the internet and I don't have HA Bridge in a hostile environment, I never saw the need to use SSL or authentication.

You can setup HA Bridge authentication via the UI, so no changes are needed in the addon to make that work.

**Comment by cbrherms** [comment]
Personally cloned the repo and added my authentication information to settings.js
Then just built from that.

**Comment by pickeld** [comment]
@cbrherms can you please explain us how to do that?
thanks !

**Comment by notoriousbdg** [comment]
Done via d28495e794f7611345331e3599de05172c592634.  Please update your addon and you can now define users.
