### ISSUE TITLE
Can you use websocket node to connect to HASS?

### ISSUE THREAD

**Issue by SchumyHao** [notoriousbdg/hassio-addons#7]
Hi 
Thank you for your great addons!

As you create node-red addon for hassio, I think you are using node-red to control hass, right?
I think node-red is a great automation tools for hass. So I use node-red to do automation job for hass on raspberry-pi.

But I found if I use docker to run hass, node-red websocket node can not connect to hass, it always shows disconnected.

This issue is not only on hassio, I try to create docker images by my self, using macVlan network, and run on different host PC, this issue always exist.

Do you have the same issue on your hassio? Any advice for me?

**Comment by notoriousbdg** [comment]
I haven't used the websocket node before, but I can't seem to get it working either.  I've been using mqtt to send messages back and forth between Home Assistant and Node-RED.
